use_frameworks!

platform :ios, '9.0'

target 'LqbCommonFramework_Example' do
  pod 'LqbCommonFramework', :path => '../'

  target 'LqbCommonFramework_Tests' do
    inherit! :search_paths

    
  end
end
