use_frameworks!

platform :ios, '9.0'

target 'LqbCommonFromework_Example' do
  pod 'LqbCommonFromework', :path => '../'

  target 'LqbCommonFromework_Tests' do
    inherit! :search_paths

    
  end
end
